/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2021-05-30 07:06:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import poly.dto.ImageDTO;
import poly.dto.UserDTO;
import poly.util.CmmUtil;

public final class MyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.ImageDTO");
    _jspx_imports_classes.add("poly.dto.UserDTO");
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	List<ImageDTO> rList = (List<ImageDTO>)request.getAttribute("rList");
	
	String ss_user_id = CmmUtil.nvl((String)session.getAttribute("ss_user_id"));
	
	int imageCnt = 0;

      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\"\n");
      out.write("          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n");
      out.write("\n");
      out.write("    <!-- Facebook Meta Tags / 페이스북 오픈 그래프 -->\n");
      out.write("    <meta property=\"og:url\" content=\"http://kindtiger.dothome.co.kr/insta\">\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\n");
      out.write("    <meta property=\"og:title\" content=\"instagram\">\n");
      out.write("    <meta property=\"og:description\" content=\"instagram clone\">\n");
      out.write("    <meta property=\"og:image\" content=\"http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg\">\n");
      out.write("    .\n");
      out.write("    <!-- Twitter Meta Tags / 트위터 -->\n");
      out.write("    <meta name=\"twitter:card\" content=\"instagram clone\">\n");
      out.write("    <meta name=\"twitter:title\" content=\"instagram\">\n");
      out.write("    <meta name=\"twitter:description\" content=\"instagram clone\">\n");
      out.write("    <meta name=\"twitter:image\" content=\"http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg\">\n");
      out.write("\n");
      out.write("    <!-- Google / Search Engine Tags / 구글 검색 엔진 -->\n");
      out.write("    <meta itemprop=\"name\" content=\"instagram\">\n");
      out.write("    <meta itemprop=\"description\" content=\"instagram clone\">\n");
      out.write("    <meta itemprop=\"image\" content=\"http://kindtiger.dothome.co.kr/insta/imgs/instagram.jpeg\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <title>instagram</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/reset.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/common.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/profile.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../resourceImg/imgs/instagram.png\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<section id=\"container\">\n");
      out.write("    <header id=\"header\">\n");
      out.write("        <section class=\"h_inner\">\n");
      out.write("\n");
      out.write("            <h1 class=\"logo\">\n");
      out.write("                <a href=\"index.html\">\n");
      out.write("                    <div class=\"sprite_insta_icon\"></div>\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"sprite_write_logo\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </h1>\n");
      out.write("\n");
      out.write("            <div class=\"search_field\">\n");
      out.write("                <input type=\"text\" placeholder=\"검색\" tabindex=\"0\">\n");
      out.write("\n");
      out.write("                <div class=\"fake_field\">\n");
      out.write("                    <span class=sprite_small_search_icon></span>\n");
      out.write("                    <span>검색</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"right_icons\">\n");
      out.write("                <a href=\"login.html\"><div class=\"sprite_compass_icon\"></div></a>\n");
      out.write("                <a href=\"profile.html\"><div class=\"sprite_user_icon_outline\"></div></a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </section>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"main_container\">\n");
      out.write("\n");
      out.write("        <section class=\"b_inner\">\n");
      out.write("\n");
      out.write("            <div class=\"hori_cont\">\n");
      out.write("                <div class=\"profile_wrap\">\n");
      out.write("                    <div class=\"profile_img\">\n");
      out.write("                        <img src=\"../resourceImg/imgs/thumb.jpeg\" alt=\"착한호랑이\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"detail\">\n");
      out.write("                    <div class=\"top\">\n");
      out.write("                        <div class=\"user_name\">KindTiger</div>\n");
      out.write("                        <a href=\"profile_edit.html\" class=\"profile_edit\">프로필편집</a>\n");
      out.write("                        <a href=\"#\" class=\"logout\">로그아웃</a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <ul class=\"middle\">\n");
      out.write("                        <li>\n");
      out.write("                            <span>게시물</span>\n");
      out.write("                            ");
 for(ImageDTO e : rList ){ 
      out.write("\n");
      out.write("                            \n");
      out.write("                           \t\t");
 imageCnt += 1;
      out.write("\n");
      out.write("                            \n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <p class=\"about\">\n");
      out.write("                        <span class=\"nick_name\">kindtigerrr</span>\n");
      out.write("                    </p>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"mylist_contents contents_container active\">\n");
      out.write("             ");
 for(ImageDTO e : rList) {
      out.write("\n");
      out.write("            \t<div class=\"pic\" name=\"image_no\" style=\"display:none\" value=\"");
      out.print(e.getImage_no());
      out.write("\">\n");
      out.write("            \t\t<a onclick=\"location.href='../image/imageDetail'\">\n");
      out.write("            \t\t\t<img src=\"../resourceImg/Image/");
      out.print(e.getSave_folder_name());
      out.write('/');
      out.print(e.getSave_file_name());
      out.write("\" name=\"user_profile\">\n");
      out.write("            \t\t</a>\n");
      out.write("            \t</div>\n");
      out.write("            ");
} 
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"bookmark_contents contents_container\">\n");
      out.write("\t\t\t<!-- 북마커 기준 게시글들 불러오기  -->\n");
      out.write("            </div>\n");
      out.write("       </section>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("<!--<script src=\"js/insta.js\"></script>-->\n");
      out.write("<script src=\"js/profile.js\"></script>\n");
      out.write("<script>\n");
      out.write("\tfunction loadUserImg(){\n");
      out.write("\t\tvar img_no = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'#img_no'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".val();\n");
      out.write("\t\tvar pagePath = '../image/imageDetail';\n");
      out.write("\t\tif($('#img_no').val() == \"\"){\n");
      out.write("\t\t\t$('#img_no').focus();\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tconsole.log(\"img_no : \" + img_no);\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\tusl : '/image/loadUserImg.do',\n");
      out.write("\t\t\ttype : 'post',\n");
      out.write("\t\t\tdata : {\n");
      out.write("\t\t\t\t\"img_no\" : img_no\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\tconsole.log(\"test\");\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar resHTML = '';\n");
      out.write("\t\t\t\tresHTML += '<div class=\"pic\" name=\"image_no\" style=\"display:none\" value=\"' + data.getSave_file_name() + '\">';\n");
      out.write("\t\t\t\tresHTML += '<a onclick=\"location.href=' + pagePath + '\">';\n");
      out.write("\t\t\t\tresHTML += '<img src=\"../resourceImg/Image/'+data.getSave_folder_name()+'/'+ data.getSave_file_name() + '\" name=\"user_profile\">';\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif( data.length == 0){\n");
      out.write("\t\t\t\t\tresHTML += '<div class=\"pic\" name=\"image_no\" style=\"display:none\" value=\"\">';\n");
      out.write("\t\t\t\t\tresHTML += '<a onclick=\"location.href=' + pagePath + '\">';\n");
      out.write("\t\t\t\t\tresHTML += '<img src=\"../resourceImg/Imgs/thumb.jpeg'\" name=\"\">';\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tfor(var i = 0; i < data.length; i++){\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tresHTML += '<div class=\"pic\" name=\"image_no\" style=\"display:none\" value=\"' + data.getSave_file_name() + '\">';\n");
      out.write("\t\t\t\t\t\tresHTML += '<a onclick=\"location.href=' + pagePath + '\">';\n");
      out.write("\t\t\t\t\t\tresHTML += '<img src=\"../resourceImg/Image/'+data.getSave_folder_name()+'/'+ data.getSave_file_name() + '\" name=\"user_profile\">';\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t})\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
