/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2021-04-19 06:53:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.image;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imageList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/reset.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/common.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../resourceImg/css/style.css\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<body>\n");
      out.write("<section id=\"container\" class=\"scroll\" id=\"autsoScroll\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <header id=\"header\">\n");
      out.write("        <section class=\"inner\">\n");
      out.write("\n");
      out.write("            <h1 class=\"logo\">\n");
      out.write("                <a href=\"index.html\">\n");
      out.write("                    <div class=\"sprite_insta_icon\"></div>\n");
      out.write("                    <div class=\"sprite_write_logo\"></div>\n");
      out.write("                </a>\n");
      out.write("            </h1>\n");
      out.write("\n");
      out.write("            <div class=\"search_box\">\n");
      out.write("                <input type=\"text\" placeholder=\"검색\" id=\"search-field\">\n");
      out.write("\n");
      out.write("                <div class=\"fake_field\">\n");
      out.write("                    <span class=\"sprite_small_search_icon\"></span>\n");
      out.write("                    <span>검색</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"right_icons\">\n");
      out.write("                <a href=\"login.html\"><div class=\"sprite_compass_icon\"></div></a>\n");
      out.write("                <a href=\"follow.html\"><div class=\"sprite_heart_icon_outline\"></div></a>\n");
      out.write("                <a href=\"profile.html\"><div class=\"sprite_user_icon_outline\"></div></a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("    </header>\n");
      out.write("    <section id=\"main_container\">\n");
      out.write("        <div class=\"inner\">\n");
      out.write("        \n");
      out.write("            <div class=\"contents_box\">\n");
      out.write("            \n");
      out.write("                <article class=\"contents\">\n");
      out.write("                    <header class=\"top\">\n");
      out.write("                        <div class=\"user_container\">\n");
      out.write("                            <div class=\"profile_img\">\n");
      out.write("                                <img src=\"../resourceImg/imgs/thumb.jpeg\" alt=\"프로필이미지\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"user_name\">\n");
      out.write("                                <div class=\"nick_name m_text\">KindTiger</div>\n");
      out.write("                                <div class=\"country s_text\">Seoul, South Korea</div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"sprite_more_icon\" data-name=\"more\">\n");
      out.write("                            <ul class=\"toggle_box\">\n");
      out.write("                               <li><input type=\"submit\" class=\"follow\" value=\"팔로우\" data-name=\"follow\"></li>\n");
      out.write("                                <li>수정</li>\n");
      out.write("                                <li>삭제</li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </header>\n");
      out.write("\n");
      out.write("                    <div class=\"img_section\">\n");
      out.write("                        <div class=\"trans_inner\">\n");
      out.write("                            <div><img src=\"../resourceImg/imgs/img_section/img01.jpg\" alt=\"visual01\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"bottom_icons\">\n");
      out.write("                        <div class=\"left_icons\">\n");
      out.write("                            <div class=\"heart_btn\">\n");
      out.write("                                <div class=\"sprite_heart_icon_outline\" name=\"39\" data-name=\"heartbeat\"></div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                           \n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"likes m_text\">\n");
      out.write("                        좋아요\n");
      out.write("                        <span id=\"like-count-39\">2,346</span>\n");
      out.write("                        <span id=\"bookmark-count-39\"></span>\n");
      out.write("                        개\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"comment_container\">\n");
      out.write("                        <div class=\"comment\" id=\"comment-list-ajax-post37\">\n");
      out.write("                            <div class=\"comment-detail\">\n");
      out.write("                                <div class=\"nick_name m_text\">dongdong2</div>\n");
      out.write("                                <div>강아지가 너무 귀여워요~!</div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"small_heart\">\n");
      out.write("                            <div class=\"sprite_small_heart_icon_outline\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"comment_field\" id=\"add-comment-post37\">\n");
      out.write("                         \n");
      out.write("                        <div class=\"upload_btn m_text\" data-name=\"comment\">게시</div>\n");
      out.write("                    </div>\n");
      out.write("                </article>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <input type=\"hidden\" id=\"page\" value=\"1\">\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("</section>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
